/**
 * JiraSoapService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.uk.genesis.jira.soap;

public interface JiraSoapService extends java.rmi.Remote {
    public com.uk.genesis.jira.soap.RemoteComment getComment(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteGroup createGroup(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteUser in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteServerInfo getServerInfo(java.lang.String in0) throws java.rmi.RemoteException;
    public com.uk.genesis.jira.soap.RemoteGroup getGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public java.lang.String login(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public boolean logout(java.lang.String in0) throws java.rmi.RemoteException;
    public com.uk.genesis.jira.soap.RemoteUser getUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteUser createUser(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue getIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue createIssue(java.lang.String in0, com.uk.genesis.jira.soap.RemoteIssue in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteNamedObject[] getAvailableActions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject[] getProjects(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue updateIssue(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteFieldValue[] in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteConfiguration getConfiguration(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteComponent[] getComponents(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject updateProject(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProject in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject getProjectByKey(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePriority[] getPriorities(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteResolution[] getResolutions(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteIssueType[] getIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteStatus[] getStatuses(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteIssueType[] getSubTaskIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteProjectRole[] getProjectRoles(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProjectRole getProjectRole(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProjectRoleActors getProjectRoleActors(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1, com.uk.genesis.jira.soap.RemoteProject in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteRoleActors getDefaultRoleActors(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void removeAllRoleActorsByNameAndType(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void removeAllRoleActorsByProject(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProject in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteProjectRole(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1, boolean in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void updateProjectRole(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProjectRole createProjectRole(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public boolean isProjectRoleNameUnique(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void addActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.uk.genesis.jira.soap.RemoteProjectRole in2, com.uk.genesis.jira.soap.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void removeActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.uk.genesis.jira.soap.RemoteProjectRole in2, com.uk.genesis.jira.soap.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void addDefaultActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.uk.genesis.jira.soap.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void removeDefaultActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.uk.genesis.jira.soap.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteScheme[] getAssociatedNotificationSchemes(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteScheme[] getAssociatedPermissionSchemes(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProjectRole in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteField[] getCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteFilter[] getSavedFilters(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteComment[] getComments(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void archiveVersion(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteVersion[] getVersions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject createProject(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4, java.lang.String in5, com.uk.genesis.jira.soap.RemotePermissionScheme in6, com.uk.genesis.jira.soap.RemoteScheme in7, com.uk.genesis.jira.soap.RemoteScheme in8) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void addComment(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteComment in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteField[] getFieldsForEdit(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssueType[] getIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public com.uk.genesis.jira.soap.RemoteIssueType[] getSubTaskIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException;
    public void addUserToGroup(java.lang.String in0, com.uk.genesis.jira.soap.RemoteGroup in1, com.uk.genesis.jira.soap.RemoteUser in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void removeUserFromGroup(java.lang.String in0, com.uk.genesis.jira.soap.RemoteGroup in1, com.uk.genesis.jira.soap.RemoteUser in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject getProjectById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void releaseVersion(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteVersion in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public boolean addAttachmentsToIssue(java.lang.String in0, java.lang.String in1, java.lang.String[] in2, byte[][] in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteAttachment[] getAttachmentsFromIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public boolean hasPermissionToEditComment(java.lang.String in0, com.uk.genesis.jira.soap.RemoteComment in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteComment editComment(java.lang.String in0, com.uk.genesis.jira.soap.RemoteComment in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteField[] getFieldsForAction(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue progressWorkflowAction(java.lang.String in0, java.lang.String in1, java.lang.String in2, com.uk.genesis.jira.soap.RemoteFieldValue[] in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue getIssueById(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteWorklog addWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteWorklog in2, java.lang.String in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteWorklog addWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteWorklog in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteWorklog addWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteWorklog in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void updateWorklogWithNewRemainingEstimate(java.lang.String in0, com.uk.genesis.jira.soap.RemoteWorklog in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void updateWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, com.uk.genesis.jira.soap.RemoteWorklog in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public void updateWorklogAndRetainRemainingEstimate(java.lang.String in0, com.uk.genesis.jira.soap.RemoteWorklog in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteWorklog[] getWorklogs(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteException;
    public boolean hasPermissionToCreateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemoteException;
    public boolean hasPermissionToDeleteWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemoteException;
    public boolean hasPermissionToUpdateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteScheme[] getNotificationSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePermissionScheme[] getPermissionSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePermissionScheme createPermissionScheme(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void deletePermissionScheme(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePermissionScheme addPermissionTo(java.lang.String in0, com.uk.genesis.jira.soap.RemotePermissionScheme in1, com.uk.genesis.jira.soap.RemotePermission in2, com.uk.genesis.jira.soap.RemoteEntity in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePermissionScheme deletePermissionFrom(java.lang.String in0, com.uk.genesis.jira.soap.RemotePermissionScheme in1, com.uk.genesis.jira.soap.RemotePermission in2, com.uk.genesis.jira.soap.RemoteEntity in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemotePermission[] getAllPermissions(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public long getIssueCountForFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue[] getIssuesFromTextSearch(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue[] getIssuesFromTextSearchWithProject(java.lang.String in0, java.lang.String[] in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteGroup updateGroup(java.lang.String in0, com.uk.genesis.jira.soap.RemoteGroup in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void deleteGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public void refreshCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject[] getProjectsNoSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteVersion addVersion(java.lang.String in0, java.lang.String in1, com.uk.genesis.jira.soap.RemoteVersion in2) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteProject createProjectFromObject(java.lang.String in0, com.uk.genesis.jira.soap.RemoteProject in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteValidationException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteScheme[] getSecuritySchemes(java.lang.String in0) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemotePermissionException, com.uk.genesis.jira.soap.RemoteAuthenticationException, com.uk.genesis.jira.soap.RemoteException;
    public com.uk.genesis.jira.soap.RemoteIssue[] getIssuesFromFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.uk.genesis.jira.soap.RemoteException;
}
