#!/bin/sh
#
# genesis       A wrapper for ant.
#
# Description:  Genesis is an environment provisioning tool capable  \  
#               of configuring the entire enterprise stack.
#
# Author:       Hussein Badakhchani 


# Environment varibles.
ANT_HOME=./apache-ant-1.7.1
CONTRIB_DIR=./contrib

USAGE="Usage: `basename $0` [-hv] [-e <enterprise>] [-d <datacentre>] [-r <rack>] [-n <node>] [-s <service>] [-i <environment>] [-a <application>]"

if [ $# -eq 1 ]; then
    continue
elif [ $# -lt 7 ]; then
    echo -e $USAGE >&2
    exit 1
else
    continue
fi

# parse command line arguments
while getopts hv:e:d:r:n:s:i:a: OPT; do
    case "$OPT" in
        h)      cat $CONTRIB_DIR/help.msg
                exit 0
                ;;
        v)      echo "`basename $0` version 0.35"
                echo "Clone URL: git://github.com/hoos/genesis.git"
                exit 0
                ;;
        e)      ENTERPRISE=$OPTARG
                ;;
        d)      DATACENTRE=$OPTARG
                ;;
        r)      RACK=$OPTARG
                ;;
        n)      NODE=$OPTARG
                ;;
        s)      SERVICE=$OPTARG
                ;;
        i)      ENVIRONMENT=$OPTARG
                ;;
        a)      APPLICATION=$OPTARG
                ;;
        \?)     # getopts issues an error message
                cat $CONTRIB_DIR/help.msg >&2
                exit 1
                ;;
    esac
done

shift `expr $OPTIND - 1`

# Run Genesis
GENESIS_CMD="$ANT_HOME/bin/ant -Denterprise=$ENTERPRISE -Ddatacentre=$DATACENTRE -Drack=$RACK -Dnode=$NODE -Dservice=$SERVICE -Denvironment=$ENVIRONMENT -Dapplication=$APPLICATION $APPLICATION:build"

$GENESIS_CMD
