================================================================================

                               WELCOME TO GENESIS

================================================================================
VERSION: 0.0.34

Release: Light
License: GPL Version 3
Website: http://www.genesis.uk.com
Contact: info@genesis.uk.com

================================================================================
USAGE UNIX

Usage: genesis [target] [argument] [target2] [argument2] ... [argument8:build]

UNIX EXAMPLES

genesis -Denterprise=MyEnterprise -Dservice=MyService -Denvironment=MyEnvironment -Ddatacentre=MyDatacentre -Drack=MyRack -Dnode=MyNode -Dapplication=MyApplication MyApplication:build

genesis -Denterprise=MyEnterprise -Dservice=MyService -Denvironment=MyEnvironment -Ddatacentre=MyDatacentre -Drack=MyRack -Dnode=MyNode -Dapplication=FC9AHS22DB FC9AHS22DB:build

================================================================================
USAGE WINDOWS

Usage: genesis.cmd [argument] [argument2] ... [argument7] 

WINDOWS EXAMPLES

genesis.cmd MyEnterprise MyDatacentre MyRack MyNode MyService MyEnvironment MyApplication

================================================================================
