#!/bin/sh
#
# Set Environment Varibles. 
#
# This script sets up the environment required for Genesis.

# Genesis version number.
GENESIS_VERSION="VERSION: 0.0.34"

# Directories.
GENESIS_HOME="."
ARCHETYPES="$GENESIS_HOME/archetypes"
BUILD="$GENESIS_HOME/build"
CONFIG="$GENESIS_HOME/config"
CONTRIB="$GENESIS_HOME/contrib"
DOCS="$GENESIS_HOME/docs"
ENGINE="$GENESIS_HOME/engine"

# Configuration hierarchy. 
LOGICAL="logical"
PHYSICAL="physical"

# Genesis build targets.

ENT_TARGET="-Denterprise"
SER_TARGET="-Dservice"
ENV_TARGET="-Denvironment"
DAT_TARGET="-Ddatacentre"
RAC_TARGET="-Drack"
NOD_TARGET="-Dnode"
APP_TARGET="-Dapplication"
APP_BUILD=":build"
